### ISSUE TITLE
[QUESTION] Why are Point and Size signed?

### ISSUE THREAD

**Issue by Abendstolz** [KenSuenobu/rust-pushrod#111]
Hello!

Pardon me, I am just a very curious person. Why is Size built of signed numbers?
https://github.com/KenSuenobu/rust-pushrod/blob/master/src/core/point.rs#L28

The same goes for Point - where the doc says: `Structure identifying a point on the screen by X and Y coordinates`, so if it never describes off-screen coordinates, why is it signed?

**Comment by KenSuenobu** [comment]
Coming from other platforms, I started with the design of keeping everything as a signed value.  Piston uses `f64` for their coordinate system, which covers a plethora of different coordinate systems.  Anything in the negative coordinate space (on 3D, from what I know) will be drawn off screen.  Same with anything on the 2D system for some windowing libraries.  I would not be surprised of some libraries cause an `assert` when drawn in negative space.  I simply followed the design moving forward, but there's no reason why I couldn't change that to `u32` or `u64` to follow the floating point values.
