### ISSUE TITLE
UI widgets do not render properly on Windows for the 'simple' example

### ISSUE THREAD

**Issue by foresterre** [KenSuenobu/rust-pushrod#121]
**Describe the bug**
Running the `simple` example using `cargo run --example simple` does not render all widgets correctly. See the screenshots below :).

**To Reproduce**

1. Clone repo on Windows 10
2. Run `cargo run --example simple` (or  `cargo run --release --example simple`)
3. Observe not properly rendered widgets

Version of pushrod `version = "0.2.9"`

**Expected behavior**

Expected well rendered UI widgets, or perhaps error log events. 

**Screenshots**
![image](https://user-images.githubusercontent.com/5955761/56523502-14517480-6537-11e9-8f80-2d67afef99f1.png)

![image](https://user-images.githubusercontent.com/5955761/56523617-3fd45f00-6537-11e9-85a7-263b7437ac90.png)

**Additional context**

Platform: Windows 10 Pro,
Toolchain: stable-x86_64-pc-windows-msvc [rustc 1.34.0 (91856ed52 2019-04-10)]

Branch 0.2.10 gives the same results :).

I was checking out this project just for fun. If I however can help by giving additional or 'better' information, feel free to ask :)

**Comment by KenSuenobu** [comment]
Wow, gotta love Windows!  Are you using a Hi-DPI screen resolution?  I suppose this probably shouldn't matter that much.  I'm on a Mac, so this renders differently for me.  What's odd is the "Desired Size" messages are showing up before the Widget IDs.  It should actually be rendering the text first, _then_ rendering the other objects.  I'll try installing Windows as a VM here and see if I can recreate.  I am also hopefully going to fix this using 3D texturing (coming next)

**Comment by maklemenz** [comment]
100-percent-dp:
![100-percent-dpi](https://user-images.githubusercontent.com/1707463/56576945-07ca2c00-65ca-11e9-9d64-f088c6296bf6.PNG)
125-percent-dpi:
![125-percent-dpi](https://user-images.githubusercontent.com/1707463/56576946-07ca2c00-65ca-11e9-83cd-70059d2bc2b0.PNG)
125-percent-dpi-releasebuild:
![125-percent-dpi-releasebuild](https://user-images.githubusercontent.com/1707463/56576947-0862c280-65ca-11e9-8984-18ef1259f781.PNG)

All on fully updated windows 10 singlemonitor setup 1.35.0-nightly, checkout of current master

**Comment by foresterre** [comment]
> Are you using a Hi-DPI screen resolution? 

No, I use a 1920x1080 display on the full HD resolution with 100% scaling:
![image](https://user-images.githubusercontent.com/5955761/56606149-1d088000-65f5-11e9-8f0f-cc7719168a6d.png)

**Comment by KenSuenobu** [comment]
Okay, weird.  I'm using 2560x1600 on my system, so it's naturally hi-DPI.  I'm going to be using GlfwWindow in the next release, which may help with rendering.  I'll also try installing Windows locally, as even Linux has the same issue with drawing.  I think it's an issue with the drawing functionality; I may have to use their scaling functionality to fix this.  I'll keep an eye on it, and keep this bug ticket opened.

**Comment by KenSuenobu** [comment]
Yes, this is what it looks like for me on Linux.  I'm using glfw, so I'm going to look into fixing this.  The rendering is identical for me.  :(

**Comment by KenSuenobu** [comment]
Fixed in 0.2.10!
