### ISSUE TITLE
PushrodCallbackEvents::mouse_button_down also triggers on keyboard presses

### ISSUE THREAD

**Issue by jbethune** [KenSuenobu/rust-pushrod#196]
According to the docs `mouse_button_down()` is

> Called when a mouse button is pressed.

But when I experimented with it, it also triggered when a keyboard key is pressed. Is this a bug or a feature?

```
    fn mouse_button_down(
         &mut self,
        _widget_id: i32,
        _button: Button,
        _widget_store: &mut WidgetStore,
        ) {

        println!( "Pressed {}", match _button {
            Button::Keyboard( key ) => format!( "{:?}", key ),
            Button::Mouse( button ) => format!( "{:?}", button ), // is triggered when keyboard is used
            Button::Controller( key ) => format!( "{:?}", key ),
            Button::Hat( hat ) => format!( "{:?}", hat ),
        } );
    }
```

**Comment by jbethune** [comment]
I dived into the code (very clean and good quality!):

Setting up callback:
https://github.com/KenSuenobu/rust-pushrod/blob/master/src/core/main.rs#L320

Based on https://docs.rs/pistoncore-input/0.28.0/input/trait.ButtonEvent.html#tymethod.button (method `button`)

The button itself can be mouse buttons but also keyboard keys (and other things):
https://docs.rs/piston_window/0.105.0/piston_window/enum.Button.html#variants

I guess the callback above can be modified to better distinguish between different types of button presses. I also noticed that right now there seems to be no way to trigger a CallbackEvent::KeyPressed event. So this callback might be a good place to create one?

**Comment by KenSuenobu** [comment]
Huh, that's very odd.  I'll have to check it out.  I am currently involved in converting the main engine to a separate project to support this.  (And for some strange reason, GitHub isn't e-mailing me new issues ...)

**Comment by jbethune** [comment]
Yes, I also did not get an e-mail from your comment. Did you notice my pull-request for this issue?

**Comment by KenSuenobu** [comment]
I did notice the pull request.  I'll probably be merging changes after I make the changes to the underlying top-level library (which I am doing with KenSuenobu/rust-pushrod-render) ... I may actually just incorporate these changes to that library so that they are part of the event engine there.

**Comment by KenSuenobu** [comment]
Does not apply to SDL2 library.  This code is working as advertised.
