### ISSUE TITLE
Documentation: Incorrect description of Engine::new() parameters

### ISSUE THREAD

**Issue by jbethune** [KenSuenobu/rust-pushrod#260]
General documentation for engine.rs is slightly incorrect:

https://github.com/KenSuenobu/rust-pushrod/blob/12ddcbbb2115239b6538faa185df74b5736e342c/src/render/engine.rs#L39

Engine::new() requires 2 parameters for width and height.

**Comment by KenSuenobu** [comment]
Code complete (0.4.20)
