### ISSUE TITLE
Add append_widget() method to render.layout.Layout trait

### ISSUE THREAD

**Issue by jbethune** [KenSuenobu/rust-pushrod#261]
The `Layout` trait currently has a method `add_widget( _widget_id, _widget_position )`. It would be nice to have a convenience method `append_widget( _widget_id )` that chooses the most sensible position automatically. For `HorizontalLayout` and `VerticalLayout` this would be at the end of the layout container. For a grid layout it would be the top-most and then left-most position that is still available.

**Comment by KenSuenobu** [comment]
Hmmm, so this would be something that could append a widget at the next free entry in the layout.  Not a bad idea.

**Comment by KenSuenobu** [comment]
Code complete (0.4.20)
