### ISSUE TITLE
Distinguish different mouse buttons

### ISSUE THREAD

**Issue by jbethune** [KenSuenobu/rust-pushrod#264]
https://github.com/KenSuenobu/rust-pushrod/blob/12ddcbbb2115239b6538faa185df74b5736e342c/src/render/callbacks.rs#L34

Right now all mouse clicks (left, right, middle, ...) are handled by this call type. But this type does not contain any information about which mouse button was pressed. Furthermore, it would be good to have different event handlers for mouse-down and mouse-up events.

**Comment by KenSuenobu** [comment]
Actually, the parameters used in the `button_clicked` callback are: button (which button was clicked, by `u8` index), the number of clicks, and the `state` indicates whether or not the button was pressed or released.  Use for a mouse_down and mouse_up event would probably make sense, though.  I'll open two tickets for those, and set them for the 0.5.x milestone.
