### ISSUE TITLE
Please add screenshot to README.md (and/or blog)

### ISSUE THREAD

**Issue by bbkane** [KenSuenobu/rust-pushrod#289]
**Is your feature request related to a problem? Please describe.**

I like to look through GUI libraries (more as a tourist than a shopper, but ...) and I love to see screenshot examples in the READMEs.

**Describe the solution you'd like**

MOAR SCREENSHOTS. Lovely screenshots, zany screenshots, screenshots that show the beauty you're working so hard to provide.

**Comment by nilsmartel** [comment]
I support this request 100%

**Comment by KenSuenobu** [comment]
All widgets will have screenshots in 0.4.27!

**Comment by KenSuenobu** [comment]
Ticket complete (0.4.27)

**Comment by bbkane** [comment]
At: https://github.com/KenSuenobu/rust-pushrod/blob/0.4.27/src/widgets/README.md .Thanks!
