### ISSUE TITLE
Window/Widget flickering under Linux sway

### ISSUE THREAD

**Issue by 0x40404040** [KenSuenobu/rust-pushrod#292]
# EPILEPSY WARNING POST CONTAINS FLICKERING GIFS
Hello, i was trying to run the examples when i stumble on this issue.

## **Describe the bug**
When running the examples on Sway(Wayland) the window and sometimes only the widgets are flickering.

On startup the window is always flickering. When clicking in the window, sometimes the window stops flickering but one to all widgets keep flickering, other times there is no more flickering is done until you keep clicking.
This happens on all examples.
I tested this on 2 different linux(fedora, arch) machines, both running sway and both having this flickering.

## **To Reproduce**
1. Clone current master branch
2. cargo run --example EXAMPLE under Sway

## ** Screenshots/Gifs **
Layout example
![layout_example](https://user-images.githubusercontent.com/58342387/74194172-0e10be00-4c59-11ea-9ed7-8f326165fb32.gif)

Progress example
![progress_example](https://user-images.githubusercontent.com/58342387/74194550-c179b280-4c59-11ea-808b-de71c22db9ae.gif)

Tile example
![tile_example](https://user-images.githubusercontent.com/58342387/74194561-cb031a80-4c59-11ea-85e1-a3dc1d2e4067.gif)

**Comment by KenSuenobu** [comment]
Yeah, I was able to recreate this in Linux when I have no GPU set up for X Windows.  I find that if I set the system to use `software()` rather than `hardware()` rendering, it works.  I might add an environment variable or command line switch to help with this.

**Comment by 0x40404040** [comment]
If desirable, I can also try to find the root of the flickering. Any thoughts/hints where to look into first, are appreciated.

**Comment by KenSuenobu** [comment]
The engine code is going to be the best bet.  `canvas.present()` is only used when the canvas draw loop needs to be refreshed, which is called on a constant basis.  What might fix it is commenting out line 133 in engine, `.accelerated()` - simply removing that and switching to software rendering may correct it.

**Comment by KenSuenobu** [comment]
This is odd.  I cannot recreate this in Ubuntu; I have used VMware on my Mac, which should operate roughly the same way that Sway would.  But, after installing the project and installing the SDL libraries, everything still works as expected.  Is it possible your Sway install isn't using hardware accelerated X, or that SDL2 needs to be configured to use your acceleration drivers somehow?

**Comment by 0x40404040** [comment]
I tried the `rust-sdl2` examples and all are working without flickering.I couldn't reproduce the problem after playing around with `rust-sdl2`. Further more i run the `rust-pushrod` examples on Gnome(wayland) and got no flickering. All examples are run with the default SDL2 VIDEODRIVER x11. So Sway and Gnome use Xwayland to launch SDL2 application. This may be a Sway/Xwayland problem.
- - -
#### SDL2 VIDEODRIVER wayland
I also tested the wayland backend of SDL2. When using SDL_VIDEODRIVER=wayland, Gnome behaves the same as Sway. Both have minor flickering of tick boxes and such. 
- - -

``Is it possible your Sway install isn't using hardware accelerated X, or that SDL2 needs to be configured to use your acceleration drivers somehow?``
My best guess, this should not be a problem since `rust-sdl2` is working. But i don't know for sure.

If you have any ideas or solutions, I'm happy to help/test.

**Comment by KenSuenobu** [comment]
It's possible it's an issue with Sway ... This is a distro that I've never heard of.  Meanwhile, I tried this with Centos, Ubuntu (16.X and 18.X distros), and had no issues.  I'm not sure what the issue might be.  I am using this with standard X, not Xwayland.  There may be an issue with the way Xwayland handles the frame buffer/3D functionality; it's hard to say.  What is your screen refresh rate set to?

**Comment by KenSuenobu** [comment]
A [quick google search](https://www.google.com/search?q=xwayland+flickering) shows multiple stacks of software having issues, not just mine.  Seems like this might be an "early adoption" issue?

**Comment by 0x40404040** [comment]
My screen refresh rate is 60Hz. Weston, the reference compositor for Wayland has the flickering problem aswell. Sorry, i can't look more into it, i lack the time and knowlage. As you already suggestion, an env variable for changing to software rendering seems to be a good solution.

**Comment by KenSuenobu** [comment]
Great, I'll look into another solution for Wayland.  I don't know if one exists (yet) but I'll do some digging.
