### ISSUE TITLE
Question: Any chance of publishing in crates.io?

### ISSUE THREAD

**Issue by Henrique194** [KenSuenobu/rust-pushrod#8]
This lib is exactly what I need for a personal project. I have seen it was yanked, any chance of republishing it?

**Comment by KenSuenobu** [comment]
Yes, it will be published to crates.io.  I need to updated the library so that it's more modern.  I just got a new job, so my time to devote to this project has gone a bit south, but it's in the plan!  I need to fix up some event functionality, so it'll be ready for a first release very soon.

**Comment by Henrique194** [comment]
Congrats on the new job! I am new to Rust, otherwise I would offer some help to build this lib.

**Comment by KenSuenobu** [comment]
No worries.  I have a lot of plans for this lib.
